language: go
go_import_path: gopkg.in/go-oauth2/redis.v4
matrix:
  include:
    - go: "1.9.7"
    - go: 1.13.x
      env: GO111MODULE=on
services:
  - redis
before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
